const list = [
    {
      id: 1,
      title: "Tata Play HD Box With Hindi Sports Kids English SD Pack",
      author: "Valid On : All Days",
      price: 2165,
      img: "https://tse1.mm.bing.net/th?id=OIP.jozYAp54YeVOTF2B4dwZ7gHaGj&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 2,
      title: "Tata Play HD Box With Hindi Super Value SD Pack",
      author: "Valid On : All Days",
      price: 2075,
      img: "https://tse2.mm.bing.net/th?id=OIP.zW_dCGR9Axvse2J5fCuEQAHaIq&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 3,
      title: "Tata Play HD Box With Hindi Sports Kids SD Pack",
      author: "Valid On : All Days",
      price: 2075,
      img: "https://tse2.mm.bing.net/th?id=OIP.nFHlm4YglE8f-7zjXjTgfwHaEK&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 4,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack",
      author: "Valid On : All Days",
      price: 2175,
      img: "https://tse2.mm.bing.net/th?id=OIP.rfDjEwgATjwlTlpJgRHqEAAAAA&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 5,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack",
      author: "Valid On : All Days",
      price: 3000,
      img: "https://tse2.mm.bing.net/th?id=OIP.NDmIMqah3-WYEyKbsIBdwwHaG5&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 6,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack",
      author: "Valid On : All Days",
      price: 4500,
      img: "https://tse1.mm.bing.net/th?id=OIP.I2B-LpetOXeklc9MrVkULQAAAA&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 7,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack ",
      author: "Valid On : All Days",
      price: 4999,
      img: "https://tse1.mm.bing.net/th?id=OIP.B4ZiRCAGpb9wy7V38vpv8gHaFk&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 8,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack",
      author: "Valid On : All Days",
      price: 6999,
      img: "https://tse1.mm.bing.net/th?id=OIP.5ff9ckQbJRZanxTeI76H8AHaEX&pid=Api&P=0",
      amount: 1,
    },
    {
      id: 9,
      title: "Tata Play HD Box With Hindi Dhamaal SD Pack",
      author: "Valid On : All Days",
      price: 3999,
      img: "https://tse4.mm.bing.net/th?id=OIP.8NwAFT-IcyRQWR_4aAoUOQAAAA&pid=Api&P=0",
      amount: 1,
    },
  ];
  
  export default list;